/**
 * Agentic PR detector — mirrors Yan Xie's detection methodology from
 * https://yan-xie-webflow.github.io/agentic-dashboard/
 *
 * Detection strategy (combined):
 *   1. Commit-level: Co-Authored-By tags matching known agentic noreply emails
 *   2. PR body: Reliable signature patterns left by Cursor Agent / Claude Code /
 *      Augment Code / OpenAI Codex
 *
 * "Full-agentic engineer" = >50% of their PRs in the window are agentic.
 * False positives excluded: the word "agentic" as a product feature, CSS cursor,
 * .augment/ config directory references.
 */

import {type AgenticStats, type PRRecord} from './types';

// ---------------------------------------------------------------------------
// Known agentic Co-Authored-By noreply addresses (commit-level signal)
// ---------------------------------------------------------------------------

const AGENTIC_COMMIT_PATTERNS: RegExp[] = [
  // Anthropic / Claude Code
  /Co-Authored-By:.*noreply@anthropic\.com/i,
  /Co-Authored-By:.*claude/i,
  // GitHub Actions
  /Co-Authored-By:.*github-actions\[bot\]/i,
  // Cursor Agent (commits authored by the agent runner)
  /Co-Authored-By:.*cursor/i,
  // Augment Code
  /Co-Authored-By:.*augment-swe\[bot\]/i,
  /Co-Authored-By:.*augmentcode/i,
  // OpenAI Codex
  /Co-Authored-By:.*codex/i,
  /Co-Authored-By:.*openai/i,
];

// ---------------------------------------------------------------------------
// Reliable PR body patterns (body-only signal — Yan's "reliable" set)
// Must be specific enough to exclude false positives.
// ---------------------------------------------------------------------------

const AGENTIC_BODY_PATTERNS: RegExp[] = [
  // Cursor Agent auto-generated PR descriptions
  /generated by cursor agent/i,
  /cursor-agent/i,
  /\bcursor agent\b.*\bgenerated\b/i,
  // Claude Code PR descriptions
  /claude code/i,
  /anthropic claude/i,
  // Standard Claude signature block in PR body
  /\[claude\]/i,
  /Co-authored-by: claude/i,
  // Copilot PR body signature
  /generated by github copilot/i,
  /copilot:.*autofix/i,
  // Augment Code PR signatures
  /generated (with|by) augment( code)?/i,
  /augment-swe\[bot\]/i,
  // OpenAI Codex PR signatures
  /generated (with|by) (openai )?codex/i,
  /openai codex/i,
];

// ---------------------------------------------------------------------------
// Exclusion patterns — known false positives to suppress
// ---------------------------------------------------------------------------

const FALSE_POSITIVE_PATTERNS: RegExp[] = [
  // "agentic" as a product feature name (not tooling signal)
  /agentic\s+(ai|platform|feature|product|experience)/i,
  // CSS cursor property changes
  /cursor:\s*(pointer|default|auto|text|move)/i,
  // Cursor IDE config files (not agent-generated code)
  /\.cursorrules/i,
  // Augment config directory (not an Augment Code signal)
  /\.augment\//i,
];

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Annotates each PR in the list with agentic detection flags (mutates in place).
 * Returns the same array for chaining.
 */
export function detectAgentic(prs: PRRecord[]): PRRecord[] {
  for (const pr of prs) {
    pr.hasAgenticCommit = checkCommits(pr.commitMessages);
    pr.hasAgenticBody = checkBody(pr.bodySnippet);
    pr.isAgentic = pr.hasAgenticCommit || pr.hasAgenticBody;
  }
  return prs;
}

/**
 * Computes aggregate agentic stats for a list of (annotated) PRs.
 */
export function computeAgenticStats(prs: PRRecord[]): AgenticStats {
  const total = prs.length;
  const agentic = prs.filter((pr) => pr.isAgentic).length;
  const agenticRate = total > 0 ? agentic / total : 0;
  return {
    total,
    agentic,
    agenticRate,
    isFullAgentic: agenticRate > 0.5,
  };
}

/**
 * Returns per-author agentic rates for a list of annotated PRs.
 * Used for individual contributor breakdown in the report.
 */
export function computePerAuthorAgenticRates(
  prs: PRRecord[]
): Map<string, AgenticStats> {
  const byAuthor = new Map<string, PRRecord[]>();
  for (const pr of prs) {
    const existing = byAuthor.get(pr.author) ?? [];
    existing.push(pr);
    byAuthor.set(pr.author, existing);
  }

  const result = new Map<string, AgenticStats>();
  for (const [author, authorPRs] of byAuthor) {
    result.set(author, computeAgenticStats(authorPRs));
  }
  return result;
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

function checkCommits(commitMessages: string[]): boolean {
  const combined = commitMessages.join('\n');
  return (
    AGENTIC_COMMIT_PATTERNS.some((p) => p.test(combined)) &&
    !FALSE_POSITIVE_PATTERNS.some((p) => p.test(combined))
  );
}

function checkBody(body: string): boolean {
  if (!body) return false;
  const hasFalsePositive = FALSE_POSITIVE_PATTERNS.some((p) => p.test(body));
  if (hasFalsePositive) return false;
  return AGENTIC_BODY_PATTERNS.some((p) => p.test(body));
}
